---
# common parameters
n_cores: &cores 3

# This is an ordered dict that contains the order in which the steps are run.
run_sequence: !!omap
  - 1: 'basic_check'
  - 2: 'infer_build'
  - 3: 'fill_data'
  - 4: 'harmonize'
  - 5: 'sort_alphabetically'
  - 6: 'write_tsv'
  - 7: 'report_min_pvalue'
  - 8: 'report_harmonization_summary'
  - 9: 'report_inflation_factors'
  - 10: 'qq_manhattan_plots'
  #- 11: 'write_vcf'

steps:
  basic_check: # see https://cloufield.github.io/gwaslab/Standardization/
    params:
      run: True
    gl_params:
      n_cores: *cores
      normalize: True
  infer_build: # see https://cloufield.github.io/gwaslab/InferBuild/
    params:
      run: True
  fill_data: # see https://cloufield.github.io/gwaslab/Conversion/#fill_data
    params:
      run: True
    gl_params:
      to_fill: ['MLOG10P', 'Z']
      overwrite: False
      extreme: True
  harmonize: # see https://cloufield.github.io/gwaslab/Harmonization/
    params:
      run: True
    gl_params:
      basic_check: False
      n_cores: *cores
  report_min_pvalue:
    params:
      run: True
      workspace: "min_P"
  sort_alphabetically:
    params:
      run: True
    gl_params:
      n_cores: *cores
  report_harmonization_summary:
    params:
      run: True
      workspace: "metal"
      workspace_subfolder: True
  report_inflation_factors:
    params:
      run: True
      workspace: "if"
  qq_manhattan_plots:
    params:
      run: True
      workspace: "plots"
      dist: 2
    gl_params:
      mode: 'mqq'
      stratified : True
      maf_bins: [[0, 0.01], [0.01, 0.05], [0.05, 1]]
      scaled: True
      build: "19"
      skip: 1
      sig_level: 5e-8
  write_tsv:
    params:
      run: True
      workspace: "output"
      workspace_subfolder: True
    gl_params:
      fmt: "gwaslab"
      to_csvargs:
        compression:
          method: "gzip"
          compresslevel: 1
          mtime: 1


# Filename transformation, e.g.: seq.3007.7.gwas.regenie.gz
filename_mask: [ True, True, True, False, False, False]
filename_sep: '.'

# IO
root_path: "results"
log_filename: "gwaspipe.log"
formatbook_path: "data/formatbook.json"     # fill this var if you want to provide a custom formatbook
