name: test

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: gwaspipe
          environment-file: environment.yml
          auto-update-conda: true
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        shell: bash -el {0}
        run: |
          make dependencies_dev
          make install

      - name: Test version
        shell: bash -el {0}
        run: |
          make test
